name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          
      - name: Build Binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o fctl-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o fctl-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o fctl-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o fctl-windows-amd64.exe
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            fctl-linux-amd64
            fctl-darwin-amd64
            fctl-darwin-arm64
            fctl-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} 